# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hidden Variables
email: d@domenic.me
description: Domenic's blog about coding and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.domenic.me" # the base hostname & protocol for your site
twitter_username: domenic
github_username:  domenic

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]
