# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hidden Variables
email: d@domenic.me
description: Domenic's blog about coding and stuff
twitter_username: domenic
github_username:  domenic

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]

timezone: UTC

# URL settings
url: "https://blog.domenic.me"
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title

# Integrations
disqus_short_name: hiddenvariables
disqus_show_comment_count: true
google_analytics_tracking_id: UA-37626687-1
